'use client'

import { useState } from 'react'
import { InteractiveSandbox } from './InteractiveSandbox'

interface TabExample {
  id: string
  title: string
  code: string
  language: string
  description: string
}

const examples: TabExample[] = [
  {
    id: 'hello',
    title: 'Hello Sandbox',
    code: `print("Hello from an isolated sandbox!")
print("This code is running in a secure container")
print("It can't access your system or break anything")`,
    language: 'python',
    description: 'Simple execution to see sandboxes in action'
  },
  {
    id: 'data',
    title: 'Data Processing',
    code: `import json

# Simulate processing customer data
data = [
    {"name": "Alice", "score": 85},
    {"name": "Bob", "score": 92},
    {"name": "Charlie", "score": 78}
]

# Process it
top_performers = [d for d in data if d["score"] > 80]
print(json.dumps(top_performers, indent=2))`,
    language: 'python',
    description: 'Real computation with data processing'
  },
  {
    id: 'files',
    title: 'File Operations',
    code: `import os

# Create a file
with open('demo.txt', 'w') as f:
    f.write('Data generated by sandbox execution\\n')
    f.write('This file exists only in this container\\n')

# Read it back
with open('demo.txt', 'r') as f:
    content = f.read()
    print("File contents:")
    print(content)

# Check environment
print(f"\\nRunning in: {os.getcwd()}")
print(f"Python version: {__import__('sys').version.split()[0]}")`,
    language: 'python',
    description: 'Full file system access within the container'
  }
]

export function SandboxTabs() {
  const [activeTab, setActiveTab] = useState('hello')
  const activeExample = examples.find(ex => ex.id === activeTab) || examples[0]

  return (
    <div className="sandbox-tabs-container">
      <div className="sandbox-info-banner">
        💡 <strong>These examples run on YOUR local sandbox.</strong> Make sure you&apos;ve set up your local sandbox first (scroll up to &quot;Try It Yourself First&quot; section).
      </div>

      <div className="sandbox-tabs">
        {examples.map(example => (
          <button
            key={example.id}
            className={`sandbox-tab ${activeTab === example.id ? 'active' : ''}`}
            onClick={() => setActiveTab(example.id)}
          >
            {example.title}
          </button>
        ))}
      </div>

      <div className="sandbox-tab-content">
        <p className="tab-description">{activeExample.description}</p>
        <InteractiveSandbox
          code={activeExample.code}
          language={activeExample.language}
          title="Python"
        />
      </div>
    </div>
  )
}
